//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        public int IdSala { get; set; }
        public string codigoDeSala { get; set; }
        public Nullable<int> CreadorDeSala { get; set; }
    
        public virtual Jugadore Jugadore { get; set; }
    }
}
